# Generated by Django 3.0.5 on 2020-04-02 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zaposleni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
                ('prezime', models.CharField(max_length=30)),
                ('br_dana_go', models.IntegerField()),
                ('br_neiskoristenih_dana', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='God_odmori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poc_odmora', models.DateField()),
                ('kraj_odmora', models.DateField()),
                ('prvi_radni_dan', models.DateField()),
                ('status_zahtjeva', models.CharField(choices=[('Planiran', 'Planiran'), ('Usaglasen', 'Usaglasen'), ('Potvrdjen', 'Potvrdjen')], default='Planiran', max_length=30)),
                ('odobrio', models.CharField(default='admin', max_length=40)),
                ('prilog', models.FileField(blank=True, upload_to='prilog')),
                ('zaposleni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odmori.Zaposleni')),
            ],
        ),
    ]
